// NBA Player Names Database
const nbaPlayers = [
    "Michael Jordan", "LeBron James", "Kobe Bryant", "Stephen Curry",
    "Kevin Durant", "Magic Johnson", "Larry Bird", "Tim Duncan",
    "Shaquille O'Neal", "Karl Malone", "John Stockton", "Charles Barkley",
    "David Robinson", "Patrick Ewing", "Hakeem Olajuwon", "Dirk Nowitzki",
    "Steve Nash", "Allen Iverson", "Ray Allen", "Paul Pierce",
    "Mitch Richmond", "Roy Hibbert", "Horace Grant", "George Karl",
    "Kawhi Leonard", "Dwyane Wade", "Chris Paul", "Damian Lillard", 
    "Luka Doncic", "James Harden", "Giannis Antetokounmpo", "Scottie Pippen",
    "Carmelo Anthony", "Russell Westbrook", "Kyrie Irving", "Kevin Garnett",
    "Anthony Davis", "Chris Bosh", "Draymond Green", "Klay Thompson",
    
 // Players with last names starting with the letter "A"
    "Alaa Abdelnaby", "Zaid Abdul-Aziz", "Kareem Abdul-Jabbar", "Mahmoud Abdul-Rauf", "Tariq Abdul-Wahad", 
    "Shareef Abdur-Rahim", "Tom Abernethy", "Forest Able", "John Abramovic", "Álex Abrines", "Precious Achiuwa", 
    "Alex Acker", "Don Ackerman", "Mark Acres", "Bud Acton", "Quincy Acy", "Alvan Adams", "Don Adams", "George Adams", 
    "Hassan Adams", "Jaylen Adams", "Jordan Adams", "Michael Adams", "O'Neal Adams", "Ray Adams", "Sparky Adams", 
    "Steven Adams", "Willie Adams", "Rafael Addison", "Bam Adebayo", "Deng Adel", "Rick Adelman", "Jeff Adrien", 
    "Arron Afflalo", "Maurice Ager", "Ochai Agbaji", "Mark Aguirre", "Blake Ahearn", "Jake Ahearn", "Danny Ainge", 
    "Matt Aitch", "Warren Ajax", "Alexis Ajinça", "Henry Akin", "Josh Akognon", "DeVaughn Akoon-Purcell", 
    "Solomon Alabi", "Mark Alarie", "Gary Alcorn", "Santi Aldama", "Furkan Aldemir", "Cole Aldrich", "LaMarcus Aldridge", 
    "Chuck Aleksinas", "Cliff Alexander", "Cory Alexander", "Courtney Alexander", "Gary Alexander", "Joe Alexander", 
    "Kyle Alexander", "Merle Alexander", "Trey Alexander", "Ty-Shon Alexander", "Victor Alexander", "Nickeil Alexander-Walker", 
    "Steve Alford", "Rawle Alkins", "Bill Allen", "Bob Allen", "Grayson Allen", "Jarrett Allen", "Jerome Allen", 
    "Kadeem Allen", "Lavoy Allen", "Lucius Allen", "Malik Allen", "Randy Allen", "Ray Allen", "Timmy Allen", 
    "Tony Allen", "Will Allen", "Odis Allison", "Lance Allred", "Darrell Allums", "Morris Almond", "Derrick Alston", 
    "Rafer Alston", "Leonard Alterman", "Peter Aluma", "Jose Alvarado", "Al Alvarez", "Bob Alwin", "John Amaechi", 
    "Ashraf Amaya", "Al-Farouq Aminu", "Ralph Amsden", "Lou Amundson", "Bob Anderegg", "Chris Andersen", "David Andersen", 
    "Alan Anderson", "Andrew Anderson", "Antonio Anderson", "Art Anderson", "Carl Anderson", "Cliff Anderson", 
    "Dan Anderson", "Derek Anderson", "Dwight Anderson", "Eric Anderson", "Gene Anderson", "Greg Anderson", 
    "J. J. Anderson", "James Anderson", "Jerome Anderson", "Justin Anderson", "Kenny Anderson", "Kim Anderson", 
    "Kyle Anderson", "Michael Anderson", "Nick Anderson", "Richard Anderson", "Ron Anderson", "Ryan Anderson", 
    "Shandon Anderson", "Willie Anderson", "Wally Anderzunas", "Ernie Andres", "Martynas Andriuškevičius", 
    "Don Anielak", "Ike Anigbogu", "Michael Ansley", "Chris Anstey", "Giannis Antetokounmpo", "Kostas Antetokounmpo", 
    "Thanasis Antetokounmpo", "Carmelo Anthony", "Cole Anthony", "Greg Anthony", "Joel Anthony", "Paul Anthony", 
    "Pero Antic", "Clyde Anton", "OG Anunoby", "Keith Appling", "Rafael Araújo", "Stacey Arceneaux", "Gerry Archibald", 
    "Nate Archibald", "Robert Archibald", "Ryan Arcidiacono", "Jim Ard", "Gilbert Arenas", "Trevor Ariza", 
    "Paul Arizin", "Joe Arlauckas", "B. J. Armstrong", "Bob Armstrong", "Brandon Armstrong", "Curly Armstrong", 
    "Darrell Armstrong", "Hilton Armstrong", "Scotty Armstrong", "Tate Armstrong", "Fred Arndt", "Jesse Arnelle", 
    "Jay Arnette", "Bob Arnzen", "Stan Arnzen", "Carlos Arroyo", "Ron Artest", "Darrell Arthur", "John Arthurs", 
    "Jamel Artis", "Bill Ash", "Ömer Aşık", "Vincent Askew", "Keith Askins", "Don Asmonga", "Dick Atha", "Chucky Atkins", 
    "Al Attles", "Chet Aubuchon", "Stacey Augmon", "D. J. Augustin", "James Augustine", "Isaac Austin", "John Austin", 
    "Ken Austin", "Carl Austing", "Deni Avdija", "Anthony Avent", "Bird Averitt", "William Avery", "Dennis Awtrey", 
    "Joël Ayayi", "Gustavo Ayon", "Jeff Ayres", "Deandre Ayton", "Kelenna Azubuike", "Udoka Azubuike"];