export const playersP = [
    "Chris Paul",
    "Tony Parker",
    "Gary Payton",
    "Gary Payton II",
    "Kendrick Perkins",
    "Paul Pierce",
    "Scottie Pippen",
    "Kristaps Porzingis",
    "Otto Porter Jr.",
    "Bobby Portis",
    "Kevin Porter Jr.",
    "Michael Porter Jr.",
    "Dwight Powell",
    "Norman Powell",
    "Julius Randle",
    "Zach Randolph",
    "Anthony Parker",
    "Jabari Parker",
    "Smush Parker",
    "Patrick Patterson",
    "Ruben Patterson",
    "Chris Paul",
    "Brandon Paul",
    "Sasha Pavlovic",
    "Gary Payton",
    "Elfrid Payton",
    "Nikola Pekovic",
    "Sam Perkins",
    "Kendrick Perkins",
    "Paul Pierce",
    "Scottie Pippen",
    "Mason Plumlee",
    "Miles Plumlee",
    "Marshall Plumlee",
    "Jakob Poeltl",
    "Quincy Pondexter",
    "Otto Porter",
    "Michael Porter",
    "Kevin Porter",
    "Terry Porter",
    "Bobby Portis",
    "Kristaps Porzingis",
    "James Posey",
    "Dwight Powell",
    "Josh Powell",
    "Norman Powell",
    "Roger Powell",
    "Alex Poythress",
    "Paul Pressey",
    "Phil Pressey"
];