export const playersZ = [
    "Zach LaVine",
    "Zach Randolph",
    "Zach Collins",
    "Zydrunas Ilgauskas",
    "Zaire Wade",
    "Zeke Nnaji",
    "Zoran Dragic",
    "Zoran Planinic",
    "Zvonimir Boban",
    "Zarko Cabarkapa",
    "Zeljko Rebraca",
    "Zendon Hamilton",
    "Zhou Qi",
    "Zaza Pachulia",
    "Zabian Dowdell",
    "Zach Auguste",
    "Zach Norvell Jr.",
    "Zaire Smith",
    "Zhaire Smith",
    "Zoran Dragic",
    "Zoran Planinic",
    "Zvi Sherf",
    "Zach Hankins",
    "Zach Lofton",
    "Zach Thomas",
    "Zena Edosomwan",
    "Zeus McClurkin",
    "Zip Gayles",
    "Ziggy Kauls",
    "Zion Williamson"
];