export const playersV = [
    "Jonas Valanciunas",
    "Fred VanVleet",
    "Jarred Vanderbilt",
    "Luc Vaudt",
    "Charlie Villanueva",
    "Anderson Varejao",
    "Greivis Vasquez",
    "Gabe Vincent",
    "Jacque Vaughn",
    "David Vaughn",
    "Rasheed Vaughn",
    "Jake Voskuhl",
    "Noah Vonleh",
    "Nikola Vucevic",
    "Gary Voce",
    "Floyd Volker",
    "Jan van Breda Kolff",
    "Nick Van Exel",
    "Keith Van Horn",
    "Darnell Valentine",
    "Ronnie Valentine",
    "John Vallely",
    "Dick Van Arsdale",
    "Tom Van Arsdale",
    "Butch Van Breda Kolff",
    "Nick Vanos",
    "David Vanterpool",
    "Ratko Varda",
    "Jeff Varem",
    "Chico Vaughn",
    "Charles Vaughn",
    "David Vaughn",
    "Jacque Vaughn",
    "James Vaughn",
    "Virgil Vaughn",
    "Bob Verga",
    "Peter Verhoeven",
    "Jan Vesely",
    "John Vivian",
    "Gary Voce",
    "Floyd Volker",
    "Alexander Volkov",
    "Jake Voskuhl",
    "Danny Vranes",
    "Slavko Vranes",
    "Stojko Vrankovic",
    "Brett Vroman",
    "Jackson Vroman",
    "Sasha Vujacic",
    "Nikola Vucevic"
];