export const playersS = [
    "Domantas Sabonis",
    "John Stockton",
    "Ben Simmons",
    "Pascal Siakam",
    "Dennis Smith Jr.",
    "Josh Smith",
    "J.R. Smith",
    "Marcus Smart",
    "Dennis Schröder",
    "Ricky Rubio",
    "D'Angelo Russell",
    "Lonnie Walker IV",
    "Collin Sexton",
    "Pascal Siakam",
    "Ben Simmons",
    "Marcus Smart",
    "Ish Smith",
    "Jason Smith",
    "Josh Smith",
    "Dennis Smith Jr.",
    "Zhaire Smith",
    "Tony Snell",
    "Marreese Speights",
    "Nik Stauskas",
    "Lance Stephenson",
    "David Stockton",
    "Jae'Sean Tate",
    "Jayson Tatum",
    "Jeff Teague",
    "Daniel Theis",
    "Klay Thompson",
    "Tristan Thompson",
    "Karl-Anthony Towns",
    "P.J. Tucker",
    "Evan Turner",
    "Jonas Valanciunas",
    "Fred VanVleet",
    "Jarred Vanderbilt",
    "Noah Vonleh",
    "Nikola Vucevic",
    "Dion Waiters",
    "Kemba Walker",
    "John Wall",
    "T.J. Warren",
    "Yuta Watanabe",
    "Russell Westbrook",
    "Hassan Whiteside",
    "Andrew Wiggins",
    "Lou Williams",
    "Robert Williams III"
];