export const playersH = [
    "James Harden",
    "Tim Hardaway",
    "Tim Hardaway Jr.",
    "Joe Harris",
    "Tobias Harris",
    "Gordon Hayward",
    "Tyler Herro",
    "Buddy Hield",
    "George Hill",
    "Solomon Hill",
    "Kirk Hinrich",
    "Grant Hill",
    "Jordan Hill",
    "Tyrone Hill",
    "Allan Houston",
    "Dwight Howard",
    "Josh Howard",
    "Al Horford",
    "Robert Horry",
    "Eddie House",
    "Ron Harper",
    "Matt Harpring",
    "Josh Hart",
    "Udonis Haslem",
    "Spencer Hawes",
    "Chuck Hayes",
    "Elvin Hayes",
    "Richard Hamilton",
    "Roy Hibbert",
    "J.J. Hickson",
    "Nene Hilario",
    "Aaron Holiday",
    "Jrue Holiday",
    "Justin Holiday",
    "Ryan Hollins",
    "Rondae Hollis-Jefferson",
    "Richaun Holmes",
    "Jeff Hornacek",
    "Dennis Hopson",
    "Al Harrington",
    "Montrezl Harrell",
    "Devin Harris",
    "Gerald Henderson",
    "John Henson",
    "Xavier Henry",
    "Roy Hibbert",
    "Mario Hezonja",
    "Daniel House",
    "Eddie House",
    "Danuel House Jr."
];

// filepath: /c:/Users/littl/NBANameGame/playerLists/playersI.js
export const playersI = [
    "Kyrie Irving",
    "Brandon Ingram",
    "Andre Iguodala",
    "Ersan Ilyasova",
    "Joe Ingles",
    "Jonathan Isaac",
    "Allen Iverson",
    "Royal Ivey",
    "Dan Issel",
    "Wesley Iwundu",
    "Zydrunas Ilgauskas",
    "Marc Jackson",
    "Byron Irvin",
    "John Isaacs",
    "Mike Iuzzolino",
    "Didier Ilunga-Mbenga",
    "Eugene Ivo",
    "Frank Iwuc",
    "Harold Irwin",
    "Brad Imes"
];

// filepath: /c:/Users/littl/NBANameGame/playerLists/playersJ.js
export const playersJ = [
    "LeBron James",
    "Magic Johnson",
    "Dennis Johnson",
    "Joe Johnson",
    "Tyler Johnson",
    "Richard Jefferson",
    "Brandon Jennings",
    "Stephen Jackson",
    "Reggie Jackson",
    "Mark Jackson",
    "Josh Jackson",
    "Jim Jackson",
    "Luke Jackson",
    "Jaren Jackson Jr.",
    "Al Jefferson",
    "Antawn Jamison",
    "DeJounte Murray",
    "Eddie Johnson",
    "Larry Johnson",
    "Kevin Johnson",
    "Wesley Johnson",
    "Vinnie Johnson",
    "James Johnson",
    "Joe Johnson",
    "Mickey Johnson",
    "Tyler Johnson",
    "Nick Johnson",
    "Orlando Johnson",
    "Chris Johnson",
    "Amir Johnson",
    "Anthony Johnson",
    "Avery Johnson",
    "Ken Johnson",
    "Larry Johnson",
    "Marques Johnson",
    "Eddie Jordan",
    "Michael Jordan",
    "DeAndre Jordan",
    "Jerome Jordan",
    "Reggie Jordan",
    "Walter Jordan",
    "Phil Jordon",
    "Johnny Jorgensen",
    "Noble Jorgensen",
    "Adonis Jordan",
    "Charles Jordan",
    "Eddie Jordan",
    "Michael Jordan",
    "Thomas Jordan",
    "Walter Jordan"
];